name = "pc-remote-control-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces для хранения данных
[[kv_namespaces]]
binding = "USERS_KV"
id = "6af8d918631b4a9290ca7a35a5196546"

[[kv_namespaces]]
binding = "DEVICES_KV"
id = "fc73e819cd5d4ab08c1c2d524e1b170d"

[[kv_namespaces]]
binding = "COMMANDS_KV"
id = "426dd8c8cd024559928fa5edc0387ff1"

[[kv_namespaces]]
binding = "RESULTS_KV"
id = "f72c498bb9bb4da6a944760043ddf960"

[[kv_namespaces]]
binding = "PAIRING_KV"
id = "31549274ee63406893fdb587d5b976f6"

# Переменные окружения (секреты)
# BOT_TOKEN нужно установить через: wrangler secret put BOT_TOKEN
